# Generated by Django 4.0.4 on 2022-04-20 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_employee', models.IntegerField(verbose_name='id пользователя')),
                ('time', models.TimeField(verbose_name='Время')),
                ('date', models.DateField(verbose_name='Дата')),
                ('condition', models.BooleanField(verbose_name='Состояние')),
            ],
        ),
        migrations.CreateModel(
            name='Type_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_application', models.DateTimeField(verbose_name='Дата подачи заявки')),
                ('date_receipt', models.DateTimeField(verbose_name='Дата приема')),
                ('id_employee', models.IntegerField(verbose_name='id пользователя')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('purpose_visit', models.CharField(max_length=50, verbose_name='Цель визита')),
                ('status', models.BooleanField(default=False, verbose_name='Состояние заявки')),
                ('text', models.TextField(verbose_name='Решение')),
                ('FIO', models.CharField(max_length=100, verbose_name='ФИО')),
                ('telephone', models.IntegerField(verbose_name='Телефон')),
                ('email', models.CharField(max_length=50, verbose_name='Почта')),
                ('type_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.type_question')),
            ],
        ),
    ]
