# Generated by Django 4.0.4 on 2022-04-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(default='New Applications', max_length=50, verbose_name='Состояние заявки'),
        ),
    ]
