# Generated by Django 4.0.4 on 2022-04-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_application_date_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_application',
            field=models.DateTimeField(verbose_name='Дата подачи заявки'),
        ),
        migrations.AlterField(
            model_name='application',
            name='date_receipt',
            field=models.DateField(verbose_name='Дата приема'),
        ),
    ]
