# Generated by Django 4.0.4 on 2022-04-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_application_date_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='type_question',
            name='id_employee',
            field=models.IntegerField(default=0, verbose_name='id_пользователя'),
        ),
    ]
