# Generated by Django 4.0.4 on 2022-04-23 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_type_question_id_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type_question',
            name='id_employee',
        ),
        migrations.CreateModel(
            name='Type_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_employee', models.IntegerField(default=0, verbose_name='id_пользователя')),
                ('id_question', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.type_question')),
            ],
        ),
    ]
