# Generated by Django 4.0.4 on 2022-04-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_type_question_id_employee_type_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='type_employee',
            name='name',
            field=models.CharField(default='1', max_length=50, verbose_name='Название'),
        ),
    ]
