# Generated by Django 4.0.4 on 2022-04-25 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_type_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 4, 25, 12, 49, 55, 465976), verbose_name='Время подачи'),
        ),
    ]
